### ISSUE TITLE
UDlextag2json.py appears not to work

### ISSUE THREAD

**Issue by Mindful** [nert-nlp/streusle#96]
I'm not sure if I'm missing something here, but it looks like there are undefined variables in `UDlextag2json.py` that cause it not to work. 

```bash
python data/streusle/conllulex2UDlextag.py data/streusle/dev/streusle.ud_dev.conllulex > dev.udlextag 
python data/streusle/UDlextag2json.py dev.udlextag 
[
Traceback (most recent call last):
  File "/Users/josh/personal/bunmyaku/data/streusle/UDlextag2json.py", line 407, in <module>
    for sent in load_sents(**vars(argparser.parse_args())):
  File "/Users/josh/personal/bunmyaku/data/streusle/UDlextag2json.py", line 315, in load_sents
    sent_conllulex += ln + '\n'
UnboundLocalError: local variable 'sent_conllulex' referenced before assignment
```

**Comment by nschneid** [comment]
Interesting. Some of those lines must have been ported from conllulex2json.py but never tested properly. Does commenting out the lines with `sent_conllulex` solve it?

**Comment by Mindful** [comment]
...actually yes, it looks like. I'll open a PR with the problem lines removed, since it looks like that at least makes the script run.

**Comment by Mindful** [comment]
Whoops, maybe not. I thought it fixed it because I started getting a bunch of JSON output, but it appears it doesn't make it through the entire file:
```
Traceback (most recent call last):
  File "/Users/josh/personal/bunmyaku/data/streusle-4.5/UDlextag2json.py", line 405, in <module>
    for sent in load_sents(**vars(argparser.parse_args())):
  File "/Users/josh/personal/bunmyaku/data/streusle-4.5/UDlextag2json.py", line 271, in load_sents
    _postproc_sent(sent)
  File "/Users/josh/personal/bunmyaku/data/streusle-4.5/UDlextag2json.py", line 135, in _postproc_sent
    assert lexe['lexlemma']==' '.join(lem for i in lexe['toknums'] for lem in [sent['toks'][i-1]['lemma']] if lem!='_'),f"In {sent['sent_id']}, MWE lemma is incorrect: {lexe} vs. {sent['toks'][lexe['toknums'][0]-1]}"
AssertionError: In reviews-105237-0001, MWE lemma is incorrect: {'lexlemma': 'go downhill _', 'lexcat': 'V.VID', 'ss': 'v.change', 'ss2': None, 'toknums': [25, 26, 27]} vs. {'#': 25, 'word': 'gone', 'lemma': 'go', 'upos': 'VERB', 'xpos': 'VBN', 'feats': 'Tense=Past|VerbForm=Part', 'head': 18, 'deprel': 'conj', 'edeps': '18:conj:but', 'misc': None, 'smwe': (2, 1), 'wmwe': None, 'lextag': 'B-V.VID-v.change'}
```

**Comment by nschneid** [comment]
This should be a step in the right direction. Still testing some things out.

**Comment by nschneid** [comment]
OK I believe the bugs are fixed. Does it work for you?

**Comment by Mindful** [comment]
@nschneid Thanks very much for the quick fixes! It does indeed work for me now - or at least, the script runs and outputs a bunch of JSON with no obvious errors.
Closing this issue for now; on the off chance that I bump into something else I'll open a different issue.
